name: take screenshot

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - screenshot

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: take screenshot
        run: |
          npx tsx screenshot/app.ts
        env:
          CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
          SECRETS: ${{ toJson(secrets) }}
