on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - screenshot

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: take screenshot
        run: |
          pushd screenshot
          npm install
          npx tsx screenshot.ts
          popd
