on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - screenshot

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: take screenshot
        run: |
          npx tsx screenshot/take-screenshot.ts
