on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - screenshot

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install ts-node
        run: npm i typescript ts-node
      - name: take screenshot
        run: |
          pushd screenshot
          npm i
          NODE_NO_WARNINGS=1 npx ts-node screenshot.ts
          popd
